####################
# site settings

title: World Classics - The world's greatest (literature) books in .txt

home:
  url:   http://worldclassics.github.io
  title: World Classics


style:
  link_color: '#000080'


########
# build settings

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false

sass:
  style: expanded

exclude:
- README.md
- .gitignore
- Gemfile
- Gemfile.lock



plugins:
- jekyll-remote-theme

remote_theme: octobook/books-twentyeighteen-theme
